# autosub core.py translation file.
# Copyright (C) 2019 BingLingFanSub
# This file is distributed under the same license as the PACKAGE package.
# BingLingFanSub <binglingfansub@gmail.com>, 2019.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-21 09:55+0800\n"
"PO-Revision-Date: 2020-03-20 20:46+0800\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh_CN\n"
"X-Generator: Poedit 2.3\n"

#: autosub/core.py:188
msgid ""
"\n"
"Converting speech regions to short-term fragments."
msgstr ""
"\n"
"按照语音区域将音频转换为多个短语音片段。"

#: autosub/core.py:189
msgid "Converting: "
msgstr "转换中： "

#: autosub/core.py:234
msgid ""
"\n"
"Sending short-term fragments to Google Speech V2 API and getting result."
msgstr ""
"\n"
"将短片段语音发送给Google Speech V2 API并得到识别结果。"

#: autosub/core.py:235 autosub/core.py:304 autosub/core.py:461
msgid "Speech-to-Text: "
msgstr "语音转文字中： "

#: autosub/core.py:276 autosub/core.py:419 autosub/core.py:512
msgid ""
"Error: Connection error happened too many times.\n"
"All works done."
msgstr ""
"错误：过多连接错误。\n"
"做完了。"

#: autosub/core.py:302
msgid ""
"\n"
"Sending short-term fragments to Google Cloud Speech V1P1Beta1 API and "
"getting result."
msgstr ""
"\n"
"将短片段语音发送给Google Cloud Speech V1P1Beta1 API并得到识别结果。"

#: autosub/core.py:427 autosub/core.py:520
msgid "Receive something unexpected:"
msgstr "收到未预期数据："

#: autosub/core.py:459
msgid ""
"\n"
"Sending short-term fragments to Xun Fei Yun WebSocket API and getting result."
msgstr ""
"\n"
"将短片段语音发送给讯飞云WebSocket API并得到识别结果。"

#: autosub/core.py:543
msgid ""
"\n"
"Translating text from \"{0}\" to \"{1}\"."
msgstr ""
"\n"
"从\"{0}\"翻译为\"{1}\"。"

#: autosub/core.py:593
msgid "Translation: "
msgstr "翻译中： "

#: autosub/core.py:656
msgid "Cancelling translation."
msgstr "取消翻译。"

#: autosub/core.py:729 autosub/core.py:788
msgid "Format \"{fmt}\" not supported. Use \"{default_fmt}\" instead."
msgstr "不支持格式\"{fmt}\"。改用\"{default_fmt}\"。"

#: autosub/core.py:861
msgid ""
"There is already a file with the same name in this location: \"{dest_name}\"."
msgstr "在此处已有同名文件：\"{dest_name}\"。"

#: autosub/core.py:864
msgid "Input a new path (including directory and file name) for output file.\n"
msgstr "为输出文件输入一个新的路径（包括路径和文件名）。\n"

#, fuzzy
#~ msgid "Cancelling transcription."
#~ msgstr "取消翻译。"

#~ msgid ""
#~ "\n"
#~ "Translating text from {0} to {1}."
#~ msgstr ""
#~ "\n"
#~ "从{0}翻译为{1}。"
